### ISSUE TITLE
blockchain cat generates invalid YAML

### ISSUE THREAD

**Issue by elviejo79** [input-output-hk/cardano-byron-cli#21]
When running: 
```bash
LASTBLOCK=deb33c62c7f5c49c13157376eab21da2dfaaf52f7ba5b130a062ecbb2b1f268e
cardano-cli blockchain cat mainnet $LASTBLOCK > example_block.yml
```

In example_bolck.yml there will be several issues.
Here is the annotated version:
```yaml
# the document should start with: --- this will make it joining files easier
header:
    # removed for brevity
body:
            tx: # wrong level of indentation tx should be a child of body and a parent of inputs,outputs and witnesses. Also it should be a list since a slot can have multiple txs 
            inputs:
                e1d1236d63033bd92e0fe3c1cf4fcf8b9d0624b4165f906ff42336cd926baf51@0 #This element should be a list since there can be more than 1 input

            outputs: #Outputs should be a list, and a dicionary to be able to separate address from amount
                DdzFFzCqrhtBe58URbj5XirGeiN4xnubfT4TUFuikp3zZC9m8HteTvdmskeknvYvaV3DsSTaJbGYjvHE3F9YkkjPNjqCgVzXLzyFKg7H 3516485.071535
                DdzFFzCqrhsuD9P4nbdTYFCjo5Lrc7fNh5Qdc76eR3SbKtrL2pnwM4qzQhTa7jgfC3Emg6aGmWfq7Mta1vTT55VQkYoi79jAbN6F71WD 10000.000000


        witnesses: # witnessess has the wrong level of indentation it's a child of tx:  and maybe should be a list
            ec177ab1a6ceb8a982d1f83b964e4ccfefe00bd677dc6fa13e447320f90e450fa2ed53ab66357e9167ff9bf945bb5970eb1bbde36f1dcc3f2df35c564462d3c6 27dd767adda7bf99c33c87f849b3f9b720a98f0821b95e524169cc68085feae8271c48d6ea25ec19a85551d32f926567b25a758b6e1d4d400ac34fcb13e0cc09 (Public Key)
```

The following files show the errors and a improved version.
[example_block_improved.yml.txt](https://github.com/input-output-hk/cardano-cli/files/2418699/example_block_improved.yml.txt)
[example_block.yml.txt](https://github.com/input-output-hk/cardano-cli/files/2418700/example_block.yml.txt)

the improved version was validated with: https://codebeautify.org/yaml-to-json-xml-csv#
