### ISSUE TITLE
feature request: make blockchain status parseable

### ISSUE THREAD

**Issue by elviejo79** [input-output-hk/cardano-byron-cli#22]
The output from `cardana-cli blockchain status mainnet` could be YAML parseable with little modifications and still remain human readable.

for example this is the current output of `blockchain status` :

```yaml
Blockchain:
   * last forward:    2018-09-25 (10h 50m 54s ago)
   * local tip hash:  deb33c62c7f5c49c13157376eab21da2dfaaf52f7ba5b130a062ecbb2b1f268e
   * local tip date:  73.8570
Peers:
 1. iohk-hosts (native: relays.cardano-mainnet.iohk.io:3000)
     * last fetch:      2018-09-25 (10h 50m 54s ago)
     * local tip hash:  deb33c62c7f5c49c13157376eab21da2dfaaf52f7ba5b130a062ecbb2b1f268e
     * local tip date:  73.8570
 2. hermes (http: http://hermes.dev.iohkdev.io/mainnet)
     * last fetch:      2018-09-24 (2days 3h 52m 42s ago)
     * local tip hash:  89d9b5a5b8ddc8d7e5a6795e9774d97faf1efea59b2caf7eaf9f8c5b32059df4
     * local tip date:  0.GENESIS
```

and this is how it would look being YAML :
```yaml
--- # three dashes to be able to join documents
Blockchain:
   last_forward:    2018-09-25 (10h 50m 54s ago) #eliminated whitespace from keys
   local_tip_hash:  deb33c62c7f5c49c13157376eab21da2dfaaf52f7ba5b130a062ecbb2b1f268e
   local_tip_date:  73.8570
Peers:  #peers becomes a list, that you can later go over with a loop
  - peer: iohk-hosts
    protocol: native
    uri: relays.cardano-mainnet.iohk.io:3000
    last_fetch:      2018-09-25 (10h 50m 54s ago)
    local_tip_hash:  deb33c62c7f5c49c13157376eab21da2dfaaf52f7ba5b130a062ecbb2b1f268e
    local_tip_date:  73.8570

  - peer: hermes
    protocol: http
    uri: http://hermes.dev.iohkdev.io/mainnet
    last_fetch:      2018-09-24 (2days 3h 52m 42s ago)
    local_tip_hash:  89d9b5a5b8ddc8d7e5a6795e9774d97faf1efea59b2caf7eaf9f8c5b32059df4
    local_tip_date:  0.GENESIS
```
the yaml version was validated with: https://codebeautify.org/yaml-to-json-xml-csv#

Demo files for your reference:
[blockchain_status_improved.yml.txt](https://github.com/input-output-hk/cardano-cli/files/2418810/blockchain_status_improved.yml.txt)
[blockchain_status.txt](https://github.com/input-output-hk/cardano-cli/files/2418811/blockchain_status.txt)
